# Generated by Django 2.2.24 on 2021-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchingRequest',
            fields=[
                ('title', models.CharField(help_text='Put here the title of the movie you need to analize', max_length=128, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Put here the year of that movie (optional)')),
            ],
        ),
    ]
