# Generated by Django 2.2.24 on 2021-08-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(help_text='Put here the title of the movie you need to analize', max_length=128, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Put here the year of that movie (optional)')),
            ],
        ),
        migrations.CreateModel(
            name='MovieVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('base_form', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchingRequest',
        ),
        migrations.AddField(
            model_name='movievocabulary',
            name='words',
            field=models.ManyToManyField(to='sub_analyze.VocabularyWord'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_analyze.MovieVocabulary'),
        ),
    ]
